/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK1_H_RPCGEN
#define _BANK1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct b1_credit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct b1_credit_1_argument b1_credit_1_argument;

struct b1_debit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct b1_debit_1_argument b1_debit_1_argument;

#define BANK1 0x20000002
#define BANK1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define B1_credit 1
extern  int * b1_credit_1(char *, int , CLIENT *);
extern  int * b1_credit_1_svc(char *, int , struct svc_req *);
#define B1_debit 2
extern  int * b1_debit_1(char *, int , CLIENT *);
extern  int * b1_debit_1_svc(char *, int , struct svc_req *);
extern int bank1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define B1_credit 1
extern  int * b1_credit_1();
extern  int * b1_credit_1_svc();
#define B1_debit 2
extern  int * b1_debit_1();
extern  int * b1_debit_1_svc();
extern int bank1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_b1_credit_1_argument (XDR *, b1_credit_1_argument*);
extern  bool_t xdr_b1_debit_1_argument (XDR *, b1_debit_1_argument*);

#else /* K&R C */
extern bool_t xdr_b1_credit_1_argument ();
extern bool_t xdr_b1_debit_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK1_H_RPCGEN */
