/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK2_H_RPCGEN
#define _BANK2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct b2_credit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct b2_credit_1_argument b2_credit_1_argument;

struct b2_debit_1_argument {
	char *arg1;
	int arg2;
};
typedef struct b2_debit_1_argument b2_debit_1_argument;

#define BANK2 0x20000003
#define BANK2_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define B2_credit 1
extern  int * b2_credit_1(char *, int , CLIENT *);
extern  int * b2_credit_1_svc(char *, int , struct svc_req *);
#define B2_debit 2
extern  int * b2_debit_1(char *, int , CLIENT *);
extern  int * b2_debit_1_svc(char *, int , struct svc_req *);
extern int bank2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define B2_credit 1
extern  int * b2_credit_1();
extern  int * b2_credit_1_svc();
#define B2_debit 2
extern  int * b2_debit_1();
extern  int * b2_debit_1_svc();
extern int bank2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_b2_credit_1_argument (XDR *, b2_credit_1_argument*);
extern  bool_t xdr_b2_debit_1_argument (XDR *, b2_debit_1_argument*);

#else /* K&R C */
extern bool_t xdr_b2_credit_1_argument ();
extern bool_t xdr_b2_debit_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK2_H_RPCGEN */
