/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bank1.h"

bool_t
xdr_b1_credit_1_argument (XDR *xdrs, b1_credit_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b1_debit_1_argument (XDR *xdrs, b1_debit_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
